# Generated by Django 4.2.7 on 2023-12-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='component',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
