# Generated by Django 4.2.7 on 2023-12-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_product_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='component',
        ),
        migrations.AddField(
            model_name='product',
            name='Arabica',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Culi',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Robusta',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
